version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: simple-library-postgres
    environment:
      POSTGRES_DB: simple-library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - library-net

  app:
    build: .
    container_name: simple-library-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/simple-library
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secretpassword
    ports:
      - "8080:8080"
    networks:
      - library-net

volumes:
  pgdata:

networks:
  library-net:
