spring:
  application:
    name: simple-library

  profiles.active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/simple-library
    username: admin
    password: secretpassword
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect



