spring:
  application:
    name: simple-library

  profiles.active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:simple-library}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect



