apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-library-app
  template:
    metadata:
      labels:
        app: simple-library-app
    spec:
      containers:
        - name: simple-library-app
          image: your-dockerhub-username/simple-library:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/simple-library
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: secretpassword
