apiVersion: v1
kind: Service
metadata:
  name: simple-library-app
spec:
  type: LoadBalancer
  selector:
    app: simple-library-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
