apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: simple-library
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secretpassword
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv

      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
